Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu1804'

  config.vm.provision :shell, path: 'provision/packages.sh'
  config.vm.provision :shell, path: 'provision/go.sh'
  config.vm.provision :shell, path: 'provision/docker.sh'
  config.vm.provision :shell, path: 'provision/nabla.sh'
  config.vm.provision :shell, path: 'provision/gvisor.sh'
  config.vm.provision :shell, path: 'provision/firecracker.sh'
  config.vm.provision :shell, path: 'provision/kata.sh'

  config.vm.provider 'vmware_fusion' do |v, override|
    v.vmx['vhv.enable'] = 'TRUE'
  end

  config.vm.synced_folder '.', '/vagrant', type: 'rsync',
    rsync__exclude: [
      '.vagrant/',
      'bundle/rootfs/',
      'rumprun/',
      'solo5/',
    ]
end
