Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu1804'
  config.vm.provision :shell, path: 'provision.sh'
  config.vm.provider 'vmware_fusion' do |v, override|
    v.vmx['vhv.enable'] = 'TRUE'
  end
  config.vm.synced_folder '.', '/vagrant'
end
